apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeless-ui
  namespace: kubeless
spec:
  rules:
  - host: kubeless-ui.demo
    http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 3000
